# Generated by Django 4.0 on 2023-08-08 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
